# Generated by Django 4.2 on 2023-04-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haberler", "0002_rename_yayımlanma_tarihi_makale_yayimlanma_tarihi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makale",
            name="yayimlanma_tarihi",
            field=models.DateField(),
        ),
    ]
