# Generated by Django 3.2.16 on 2023-04-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0003_alter_makale_yayimlanma_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='güncellenme_tarihi',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='makale',
            name='yaratilma_tarihi',
            field=models.DateField(auto_now_add=True),
        ),
    ]
