# Generated by Django 3.2.16 on 2023-04-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0004_auto_20230404_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='güncellenme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='makale',
            name='yaratilma_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='makale',
            name='yayimlanma_tarihi',
            field=models.DateTimeField(),
        ),
    ]
