# Generated by Django 3.2.16 on 2023-04-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0005_auto_20230404_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='yayimlanma_tarihi',
            field=models.DateField(),
        ),
    ]
